### ISSUE TITLE
Array parser assumes value is string. Improve by allowing objects/records in arrays?

### ISSUE THREAD

**Issue by TomiS** [MargaretKrutikova/bs-query-string#4]
Hi. Thanks for a nice library.

Wondering if array parser could be improved by allowing other types than string. It's quite possible to serialize e.g. objects inside arrays in url search so would be cool if this lib would allow that somehow too.

I guess being able to provide custom parser would for some items would be a start, but it seems the types also assume string

**Comment by TomiS** [comment]
Ok, I realized this improvement might be a bit unnecessary or even wrong... and also I don't need it after all. So closing. Sorry for the notification spam.

**Comment by MargaretKrutikova** [comment]
Hello! No problem at all, I am glad you found this library useful :)
And I am open to any suggestions/improvements.

**Comment by MargaretKrutikova** [comment]
Now when I think about it, it seems really useful to have a custom parser for arrays, so I am curious to look into it.
Could you share why you thought this improvement would be unnecessary?

**Comment by TomiS** [comment]
@MargaretKrutikova Well, I have this use case where I store small objects in to an array in URL. I recall I originally tried having them directly serialized and look something like this:
```js
// might be slightly invalid syntax, but I guess you get the point
?param[0]['id']=abcabc123&param[0]['index']=3
```
Then I ended up changing that to 
```js
?param[0]=jsonObjectAsBase64EncodedString
```
because (I think) it ended up being more reliable that way. If I remember correctly, there might be some limitations to what one can express in URL (char sets, etc) that do not apply to objects in general, so json with base64 encoding seemed sensible.

I was able to implement decoding like this:
```reason
type urlQueryItem = {
  id: string,
  index: int,
};
let parseQueryItem = (jsonBase64: string): option(urlQueryItem) => {
  let decoder = json =>
    Json.Decode.{
      id: json |> field("id", string),
      index: json |> field("index", int),
    };
  switch (Json.parse(Webapi__Base64.atob(jsonBase64))) {
  | Some(parsed) => Some(decoder(parsed))
  | None => None
  };
};

let parseQuery = (qs: string): urlQuery => {
  let obj = BsQueryString.Parse.toQueryObj(qs);
  BsQueryString.Parse.{
    items:
      obj
      |> optional(item("parents", array))
      |> (
        fun
        | Some(arr) => {
            Belt.Array.keepMap(arr, (str: string) => parseQueryItem(str));
          }
        | None => [||]
      ),
  };
};
```
That said, I cannot really say whether or not it is useful to have a custom parser for array items. Maybe it'd be possible to make the `parseQuery` function in my example a bit shorter with one. Or maybe it has other use cases. I just closed this ticket because I was no more able to reason about it :)

**Comment by MargaretKrutikova** [comment]
Thanks for the example! I have played around with the API a bit, and added `single` and `array` instead of `item` that allow custom parsers into a branch.
Your code would look something like this:

```reason
let parseQueryItem = (jsonBase64: string): option(urlQueryItem) => {
    let decoder = json =>
      Json.Decode.{
        id: json |> field("id", string),
        index: json |> field("index", int),
      };
    Json.parse(Webapi__Base64.atob(jsonBase64))->Belt.Option.map(decoder);
  };

  let parseQuery = (qs: string) => {
    let obj = Parse.toQueryObj(qs);
    let parsedItems =
      Parse.(obj |> withDefault([||], array("items", parseQueryItem)))
      ->Belt.Array.keepMap(value => value);

    {items: parsedItems};
  };
```

I am not sure it made it so much better though, maybe in a very complicated case it would make more sense, but I think the code in your example looks pretty neat as it is now 😄 

I pushed the code with custom parsers into a branch [`custom-parser`](https://github.com/MargaretKrutikova/bs-query-string/tree/custom-parser), just in case if you were curios. Otherwise I will think about incorporating it into `master` if there is a need in such a feature later.

**Comment by TomiS** [comment]
Nice. I'd say your code is slightly clearer (and thus better). I'm wondering if the `Belt.Array.keepMap` could even be part of your `array` implementation. The sole purpose of that is to clean up items that have failed to parse correctly, so one could argue there should be none of them in the first place. Not sure though, might be too opinionated.
