### ISSUE TITLE
Parser fails if search starts with question mark

### ISSUE THREAD

**Issue by TomiS** [MargaretKrutikova/bs-query-string#5]
Hi, I noticed that the parser cannot manage a situation where the search string starts with a question mark `?`. Given that e.g. ReasonReact router includes the question mark in the search string, I think it'd be convenient if this lib could just parse it out automatically.

**Comment by MargaretKrutikova** [comment]
Hej! Sorry for the late response. I can fix it pretty quickly I think 🙂
